apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: blackbox-prober
    app.kubernetes.io/instance: observatorium-up
    app.kubernetes.io/name: observatorium-up
    app.kubernetes.io/version: master-2020-06-03-8a20b4e
  name: observatorium-up
  namespace: observatorium
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: blackbox-prober
    app.kubernetes.io/instance: observatorium-up
    app.kubernetes.io/name: observatorium-up
